import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { Data } from "../helpers/db.js";
import { useState } from "react";
import Card from "../components/Card/Card.js";
import TitleBar from "../components/TitleBar/TitleBar.js";
import styled from "styled-components";
import CardList from "../components/CardList/CardList.js";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [data, setData] = useState(Data);
  console.log(data);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <StyledApp>
        <TitleBar />
        <CardList data={data} />
      </StyledApp>
    </>
  );
}
const StyledApp = styled.div`
  width: 50%;
  border: solid 0.5px black;
  margin-left: 25%;
  margin-right: 25%;
`;
