import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { Data } from "../helpers/db.js";
import { useState } from "react";
import Card from "../components/Card/Card.js";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [data, setData] = useState(Data);
  console.log(data);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ul>
        {data.map((newData) => (
          <li key={newData.id}>
            <Card data={newData} />
          </li>
        ))}
      </ul>
    </>
  );
}
